### ISSUE TITLE
Implement "Post" button function

### ISSUE THREAD

**Issue by EBryceZ** [cse442-spring-2020-offering/cse442-project-dr-hertz-fan-club#38]
Task Test:
Allow server to receive item data.

**Comment by hjoshi3** [comment]
Test1:

- [x] You click on the textbook listing button
- [x] You click on the post button to make sure it doesn't let you post
- [x] you fill out the form
- [x] when you click on the post button it takes you to the main page and on top, it shows the message "You have successfully Posted"
- [x] It shows up on the textbook table

Test2:

- [x] You click on the housing listing button
- [x] You click on the post button to make sure it doesn't let you post
- [x] you fill out the form
- [x] when you click on the post button it takes you to the main page and on top, it shows the message "You have successfully Posted"
- [x] It shows up on the house table

Test3:

- [x] You click on the Roommate listing button
- [x] You click on the post button to make sure it doesn't let you post
- [x] you fill out the form
- [x] when you click on the post button it takes you to the main page and on top, it shows the message "You have successfully Posted"
- [x] It shows up on the roommate table

Test4:
- [x] You click on the General listing button
- [x] You click on the post button to make sure it doesn't let you post
- [x] you fill out the form
- [x] when you click on the post button it takes you to the main page and on top, it shows the message "You have successfully Posted"
- [x] It shows up on the everything table
